import { useMemo, useState } from 'react'
import type { ModuleKey, Role, Student, User } from './types'
import {
  Activity, Archive, ArrowUpRight, BadgeCheck, BarChart3, Bell, BookOpen, CalendarDays, Check, ChevronDown,
  CircleDollarSign, ClipboardCheck, Clock3, FileBarChart, FileText, GraduationCap, LayoutDashboard, LogOut,
  Menu, MoreHorizontal, Printer, Search, Settings, ShieldCheck, Sparkles, UserPlus, Users, WalletCards, X, Plus, Download
} from 'lucide-react'

const studentsSeed: Student[] = [
  { id: 1, admissionNo: 'HA-24001', name: 'Ayesha Khan', nameUr: 'عائشہ خان', father: 'Imran Khan', className: 'Grade 8', section: 'A', contact: '0300 1234567', status: 'Active', fee: 0, attendance: 96, avatar: 'AK' },
  { id: 2, admissionNo: 'HA-24002', name: 'Muhammad Hamza', nameUr: 'محمد حمزہ', father: 'Tariq Ahmed', className: 'Grade 7', section: 'B', contact: '0312 8877665', status: 'Active', fee: 4500, attendance: 88, avatar: 'MH' },
  { id: 3, admissionNo: 'HA-24003', name: 'Fatima Noor', nameUr: 'فاطمہ نور', father: 'Nadeem Raza', className: 'Grade 9', section: 'A', contact: '0333 6655443', status: 'Active', fee: 0, attendance: 93, avatar: 'FN' },
  { id: 4, admissionNo: 'HA-24004', name: 'Ali Raza', nameUr: 'علی رضا', father: 'Sohail Raza', className: 'Grade 6', section: 'A', contact: '0321 9900112', status: 'Active', fee: 9000, attendance: 79, avatar: 'AR' },
  { id: 5, admissionNo: 'HA-24005', name: 'Zainab Iqbal', nameUr: 'زینب اقبال', father: 'Waqas Iqbal', className: 'Grade 5', section: 'C', contact: '0301 4545454', status: 'Active', fee: 0, attendance: 98, avatar: 'ZI' },
]
const nav: { key: ModuleKey; label: string; icon: any; owner?: boolean }[] = [
  { key: 'dashboard', label: 'Dashboard', icon: LayoutDashboard }, { key: 'students', label: 'Students & Admissions', icon: GraduationCap },
  { key: 'classes', label: 'Classes & Sections', icon: BookOpen }, { key: 'fees', label: 'Fee Management', icon: WalletCards },
  { key: 'attendance', label: 'Attendance', icon: ClipboardCheck }, { key: 'exams', label: 'Exams & Results', icon: FileBarChart },
  { key: 'staff', label: 'Staff & HR', icon: Users }, { key: 'timetable', label: 'Timetable', icon: CalendarDays },
  { key: 'reports', label: 'Reports & Analytics', icon: BarChart3 }, { key: 'expenses', label: 'Expenses', icon: CircleDollarSign, owner: true },
  { key: 'settings', label: 'Settings & Backup', icon: Settings, owner: true }, { key: 'cards', label: 'ID Cards & Certificates', icon: BadgeCheck },
]
const money = (n: number) => `Rs. ${n.toLocaleString()}`

function Login({ onLogin }: { onLogin: (u: User) => void }) {
  const [role, setRole] = useState<Role>('owner'); const [password, setPassword] = useState('')
  return <div className="min-h-screen bg-[#f4f6fb] flex items-center justify-center p-6">
    <div className="w-full max-w-[1040px] grid lg:grid-cols-[1.05fr_.95fr] bg-white rounded-[28px] overflow-hidden shadow-[0_24px_80px_rgba(36,47,80,.12)]">
      <div className="hidden lg:flex bg-[#172a62] p-14 text-white flex-col justify-between relative overflow-hidden">
        <div className="absolute -right-20 -top-20 size-80 rounded-full border-[32px] border-white/5"/><div className="absolute -left-24 -bottom-32 size-96 rounded-full bg-[#efb65b]/10"/>
        <div><div className="flex items-center gap-3 font-bold text-xl"><span className="size-10 rounded-xl bg-[#eeb45a] text-[#172a62] grid place-items-center"><GraduationCap size={24}/></span> Horizon Academy</div>
          <div className="mt-28 max-w-sm"><p className="text-[#efb65b] font-bold tracking-[.18em] text-xs uppercase">Offline school management</p><h1 className="text-5xl leading-[1.1] mt-4">Everything your school needs, in one place.</h1><p className="text-white/65 mt-6 text-lg leading-7">Simple, secure and designed for the way your school works.</p></div></div>
        <div className="text-sm text-white/45">Academic year 2024–25 <span className="mx-2">•</span> Local desktop edition</div>
      </div>
      <div className="p-8 sm:p-14 flex flex-col justify-center"><div className="lg:hidden flex items-center gap-3 font-bold text-xl mb-14"><span className="size-10 rounded-xl bg-[#172a62] text-white grid place-items-center"><GraduationCap size={24}/></span> Horizon Academy</div>
        <p className="text-sm text-slate-500">Welcome back</p><h2 className="text-3xl mt-2">Sign in to your workspace</h2><p className="text-slate-500 mt-3">Use your local school account to continue.</p>
        <div className="mt-9"><label className="label">Sign in as</label><div className="grid grid-cols-2 gap-3">{(['owner','manager'] as Role[]).map(r=><button key={r} onClick={()=>setRole(r)} className={`p-4 rounded-xl border text-left transition ${role===r?'border-[#263d83] bg-[#f0f3ff] ring-2 ring-[#263d83]/10':'border-slate-200 hover:border-slate-300'}`}><div className="font-bold capitalize">{r}</div><div className="text-xs text-slate-500 mt-1">{r==='owner'?'Full access':'Operations only'}</div></button>)}</div></div>
        <label className="label mt-6">Username</label><input className="input" defaultValue={role==='owner'?'owner':'manager'} placeholder="Enter username"/>
        <label className="label mt-5">Password</label><input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter password"/>
        <div className="flex justify-between items-center mt-4 text-sm"><label className="flex gap-2 items-center text-slate-600"><input type="checkbox" defaultChecked className="accent-[#263d83]"/> Remember me</label><button className="text-[#263d83] font-bold">Forgot password?</button></div>
        <button onClick={()=>onLogin({ username: role, name: role==='owner'?'Muhammad Ali':'Sana Ahmed', role })} className="w-full mt-8 py-3.5 rounded-xl bg-[#263d83] hover:bg-[#1c2f6b] text-white font-bold shadow-lg shadow-[#263d83]/20">Sign in securely <ArrowUpRight className="inline ml-1" size={17}/></button>
        <p className="text-center text-xs text-slate-400 mt-8 flex items-center justify-center gap-2"><ShieldCheck size={14}/> Your data stays on this computer</p>
      </div>
    </div>
  </div>
}

function Stat({ label, value, note, icon: Icon, tone='blue' }: any) { return <div className="card p-5"><div className="flex justify-between"><div><p className="text-sm text-slate-500">{label}</p><h3 className="text-2xl mt-2">{value}</h3></div><div className={`size-11 rounded-xl grid place-items-center ${tone==='gold'?'bg-amber-50 text-amber-600':tone==='green'?'bg-emerald-50 text-emerald-600':'bg-indigo-50 text-indigo-600'}`}><Icon size={21}/></div></div><p className="text-xs text-slate-500 mt-4">{note}</p></div> }
function Badge({ children, color='blue' }: any) { return <span className={`badge ${color}`}>{children}</span> }
function Table({ headers, children }: any) { return <div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-slate-50/80 text-left text-xs uppercase tracking-wider text-slate-400">{headers.map((h:string)=><th key={h} className="px-5 py-3.5 font-bold">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{children}</tbody></table></div></div> }

function App() {
  const [user, setUser] = useState<User | null>(null); const [active, setActive] = useState<ModuleKey>('dashboard'); const [students, setStudents] = useState(studentsSeed); const [query, setQuery] = useState(''); const [showAdd, setShowAdd] = useState(false)
  if (!user) return <Login onLogin={(next) => { setActive('dashboard'); setUser(next) }}/>
  const visibleNav = nav.filter(n=>!n.owner || user.role==='owner')
  const title = nav.find(n=>n.key===active)?.label || 'Dashboard'
  const filtered = students.filter(s => `${s.name} ${s.admissionNo} ${s.className}`.toLowerCase().includes(query.toLowerCase()))
  const addStudent = (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const f=new FormData(e.currentTarget); const name=String(f.get('name')||'New Student'); setStudents([{id:Date.now(), admissionNo:`HA-24${String(students.length+1).padStart(3,'0')}`, name, nameUr:String(f.get('urdu')||'—'), father:String(f.get('father')||'—'), className:String(f.get('class')||'Grade 1'), section:'A', contact:String(f.get('contact')||'—'), status:'Active', fee:0, attendance:100, avatar:name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()},...students]); setShowAdd(false) }
  return <div className="min-h-screen flex bg-[#f7f8fc]">
    <aside className="no-print w-[264px] bg-[#172a62] text-white flex-shrink-0 hidden md:flex flex-col"><div className="h-[82px] px-6 flex items-center gap-3 border-b border-white/10"><div className="size-10 bg-[#efb65b] text-[#172a62] rounded-xl grid place-items-center"><GraduationCap size={23}/></div><div><div className="font-extrabold tracking-tight">Horizon Academy</div><div className="text-[10px] uppercase tracking-widest text-white/45 mt-0.5">School OS</div></div></div>
      <div className="px-4 pt-7 pb-3 text-[10px] uppercase tracking-[.18em] text-white/35 font-bold">Workspace</div><nav className="px-3 space-y-1 overflow-y-auto scrollbar flex-1">{visibleNav.map(n=>{const I=n.icon; return <button key={n.key} onClick={()=>setActive(n.key)} className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm text-left transition ${active===n.key?'bg-white text-[#172a62] font-bold shadow-sm':'text-white/65 hover:bg-white/10 hover:text-white'}`}><I size={17}/>{n.label}{n.owner&&<span className="ml-auto text-[9px] bg-amber-400/20 text-amber-300 px-1.5 py-0.5 rounded">OWNER</span>}</button>})}</nav>
      <div className="p-4"><div className="rounded-xl bg-white/8 p-3.5 text-xs text-white/65"><div className="flex items-center gap-2 text-[#efb65b] font-bold"><Sparkles size={14}/> Offline mode</div><p className="mt-2 leading-5">All changes are saved locally on this device.</p></div></div>
    </aside>
    <main className="flex-1 min-w-0"><header className="no-print h-[82px] bg-white border-b border-slate-200/80 flex items-center justify-between px-5 lg:px-9"><div className="flex items-center gap-3"><button className="md:hidden p-2"><Menu size={20}/></button><div><p className="text-xs text-slate-400">Thursday, 20 August 2026</p><h2 className="text-xl mt-1">{title}</h2></div></div><div className="flex items-center gap-5"><button className="relative text-slate-400"><Bell size={19}/><span className="absolute -right-1 -top-1 size-2 bg-rose-500 rounded-full"/></button><div className="h-8 w-px bg-slate-200"/><div className="flex items-center gap-2.5"><div className="size-9 rounded-full bg-[#e8edff] text-[#263d83] grid place-items-center font-bold text-sm">{user.name.split(' ').map(x=>x[0]).join('')}</div><div className="hidden sm:block"><div className="text-sm font-bold">{user.name}</div><div className="text-[11px] text-slate-400 capitalize">{user.role} account</div></div><button onClick={()=>setUser(null)} title="Sign out"><LogOut size={16} className="text-slate-400 ml-2"/></button></div></div></header>
      <div className="p-5 lg:p-9 max-w-[1500px]">{active==='dashboard'&&<Dashboard role={user.role} setActive={setActive}/>}
        {active==='students'&&<Students students={filtered} query={query} setQuery={setQuery} onAdd={()=>setShowAdd(true)}/>}
        {active==='classes'&&<Classes/>}{active==='fees'&&<Fees/>}{active==='attendance'&&<Attendance/>}{active==='exams'&&<Exams/>}{active==='staff'&&<Staff role={user.role}/>}
        {active==='timetable'&&<Timetable/>}{active==='reports'&&<Reports role={user.role}/>}
        {active==='expenses'&&user.role==='owner'&&<Expenses/>}{active==='settings'&&user.role==='owner'&&<SettingsPage/>}{active==='cards'&&<Cards/>}
      </div>
    </main>
    {showAdd&&<div className="fixed inset-0 bg-slate-900/40 z-30 flex items-center justify-center p-4"><form onSubmit={addStudent} className="bg-white rounded-2xl w-full max-w-2xl p-7 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-xl">New admission</h2><p className="text-sm text-slate-500 mt-1">Admission number will be generated automatically.</p></div><button type="button" onClick={()=>setShowAdd(false)}><X/></button></div><div className="grid sm:grid-cols-2 gap-4 mt-7">{[['name','Student name (English)'],['urdu','Student name (Urdu)'],['father','Father / guardian name'],['contact','Contact number'],['class','Applying for class']].map(([n,l])=><label key={n} className="label">{l}<input name={n} className="input mt-2" required={n==='name'}/></label>)}</div><div className="flex justify-end gap-3 mt-7"><button type="button" className="btn-secondary" onClick={()=>setShowAdd(false)}>Cancel</button><button className="btn-primary"><UserPlus size={16}/> Create admission</button></div></form></div>}
  </div>
}

function PageHead({ eyebrow, title, desc, action }: any) { return <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 mb-7"><div><p className="eyebrow">{eyebrow}</p><h1 className="text-3xl mt-1">{title}</h1><p className="text-sm text-slate-500 mt-2">{desc}</p></div>{action}</div> }
function Dashboard({ role, setActive }: { role: Role; setActive: (x:ModuleKey)=>void }) { return <><PageHead eyebrow="Overview" title={`Good morning, ${role==='owner'?'Muhammad':'Sana'}`} desc="Here’s what’s happening at Horizon Academy today." action={<button className="btn-secondary" onClick={()=>window.print()}><Printer size={16}/> Print overview</button>}/><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4"><Stat label="Total students" value="1,248" note="+28 admissions this term" icon={GraduationCap}/><Stat label="Fee collected today" value="Rs. 84,500" note="↑ 12.5% from yesterday" icon={WalletCards} tone="gold"/><Stat label="Attendance today" value="94.2%" note="1,176 present · 72 absent" icon={ClipboardCheck} tone="green"/>{role==='owner'?<Stat label="Monthly net income" value="Rs. 1.2m" note="After Rs. 438k expenses" icon={BarChart3}/>:<Stat label="Fee due today" value="Rs. 126,000" note="32 students pending" icon={Clock3} tone="gold"/>}</div>
  <div className="grid xl:grid-cols-[1.35fr_.8fr] gap-5 mt-5"><div className="card p-6"><div className="flex justify-between items-center"><div><h3>Fee collection overview</h3><p className="text-xs text-slate-400 mt-1">August 2026 · Last 7 days</p></div><button onClick={()=>setActive('reports')} className="text-xs text-[#263d83] font-bold">View report <ArrowUpRight size={14} className="inline"/></button></div><div className="h-48 flex items-end gap-3 sm:gap-6 mt-7 px-2">{[42,58,45,76,63,84,70].map((h,i)=><div className="flex-1 h-full flex flex-col justify-end items-center gap-2" key={i}><div className="w-full max-w-10 bg-[#dce3ff] rounded-t-md hover:bg-[#263d83] transition" style={{height:`${h}%`}}/><span className="text-[10px] text-slate-400">{['M','T','W','T','F','S','S'][i]}</span></div>)}</div></div><div className="card p-6"><div className="flex justify-between"><h3>Quick actions</h3><MoreHorizontal size={19} className="text-slate-400"/></div><div className="grid grid-cols-2 gap-3 mt-5">{[['students','New admission',UserPlus],['attendance','Mark attendance',ClipboardCheck],['fees','Collect fee',WalletCards],['exams','Enter marks',FileText]].map(([k,l,I]:any)=><button onClick={()=>setActive(k)} key={k} className="text-left rounded-xl border border-slate-100 p-3 hover:border-[#bdc8f2] hover:bg-indigo-50/40"><div className="size-8 rounded-lg bg-indigo-50 text-[#263d83] grid place-items-center"><I size={16}/></div><div className="text-xs font-bold mt-3">{l}</div></button>)}</div></div></div>
  <div className="card p-6 mt-5"><div className="flex justify-between items-center mb-4"><h3>Upcoming exams</h3><button onClick={()=>setActive('exams')} className="text-xs text-[#263d83] font-bold">See all</button></div><div className="grid md:grid-cols-3 gap-3">{[['Mid-Term Examination','Grade 8 · Grade 9','26 Aug 2026'],['Monthly Assessment','Grade 5 · Grade 6','02 Sep 2026'],['Final Term Examination','All classes','18 Nov 2026']].map(x=><div className="rounded-xl bg-slate-50 p-4 flex justify-between items-center" key={x[0]}><div><div className="font-bold text-sm">{x[0]}</div><div className="text-xs text-slate-500 mt-1">{x[1]}</div></div><div className="text-xs text-[#263d83] font-bold">{x[2]}</div></div>)}</div></div></> }
function Students({ students, query, setQuery, onAdd }: any) { return <><PageHead eyebrow="Admissions" title="Students & admissions" desc="Manage student profiles, family links and academic records." action={<button className="btn-primary" onClick={onAdd}><Plus size={17}/> New admission</button>}/><div className="flex flex-col sm:flex-row gap-3 mb-5"><div className="relative flex-1"><Search size={17} className="absolute left-3 top-3 text-slate-400"/><input className="input pl-10" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name, admission number or class..."/></div><button className="btn-secondary"><Download size={16}/> Export list</button></div><Table headers={['Student','Admission #','Class / section','Guardian contact','Attendance','Fee balance','Status','']} >{students.map((s:Student)=><tr key={s.id} className="hover:bg-slate-50"><td className="px-5 py-4"><div className="flex gap-3 items-center"><div className="size-9 rounded-full bg-[#e8edff] text-[#263d83] grid place-items-center text-xs font-bold">{s.avatar}</div><div><div className="font-bold">{s.name}</div><div className="text-xs text-slate-400" dir="rtl">{s.nameUr}</div></div></div></td><td className="px-5 font-mono text-xs text-slate-500">{s.admissionNo}</td><td className="px-5">{s.className} <span className="text-slate-400">· {s.section}</span></td><td className="px-5 text-slate-500">{s.contact}</td><td className="px-5"><span className={s.attendance<85?'text-rose-600':'text-emerald-600'}>{s.attendance}%</span></td><td className="px-5 font-medium">{s.fee?money(s.fee):<span className="text-emerald-600">Cleared</span>}</td><td className="px-5"><Badge color="green">{s.status}</Badge></td><td className="px-5"><button className="p-2 hover:bg-slate-100 rounded-lg"><MoreHorizontal size={17}/></button></td></tr>)}</Table></> }
function Classes(){return <><PageHead eyebrow="Academic setup" title="Classes & sections" desc="Configure classes, sections, teachers and subjects." action={<button className="btn-primary"><Plus size={17}/> Add class</button>}/><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{[['Nursery','2 sections','42 students','Ms. Hina Malik'],['Grade 1','3 sections','86 students','Mr. Bilal Khan'],['Grade 5','3 sections','118 students','Ms. Sara Ali'],['Grade 7','2 sections','94 students','Mr. Omar Farooq'],['Grade 8','2 sections','82 students','Ms. Ayesha Riaz'],['Grade 9','2 sections','76 students','Mr. Hassan Shah']].map(x=><div className="card p-5 hover:-translate-y-0.5 transition" key={x[0]}><div className="flex justify-between"><div className="size-10 rounded-xl bg-indigo-50 text-[#263d83] grid place-items-center"><BookOpen size={19}/></div><button><MoreHorizontal size={18} className="text-slate-400"/></button></div><h3 className="mt-5">{x[0]}</h3><div className="flex gap-4 text-xs text-slate-500 mt-2"><span>{x[1]}</span><span>{x[2]}</span></div><div className="border-t border-slate-100 mt-5 pt-3 text-xs text-slate-500">Class teacher <b className="text-slate-700 ml-1">{x[3]}</b></div></div>)}</div></>}
function Fees(){const [paid,setPaid]=useState<number[]>([1,3]); return <><PageHead eyebrow="Finance · Collection" title="Fee management" desc="Collect fees, manage challans and track defaulters." action={<button className="btn-primary"><Plus size={17}/> Generate challans</button>}/><div className="grid sm:grid-cols-3 gap-4 mb-5"><Stat label="Collected this month" value="Rs. 1.84m" note="78% of expected collection" icon={WalletCards} tone="green"/><Stat label="Outstanding balance" value="Rs. 486k" note="142 students with dues" icon={Clock3} tone="gold"/><Stat label="Receipts issued" value="386" note="August 2026" icon={FileText}/></div><Table headers={['Student','Month','Due date','Amount due','Status','Action']}>{[['Ayesha Khan','August 2026','10 Aug 2026',8500,1],['Muhammad Hamza','August 2026','10 Aug 2026',8500,2],['Fatima Noor','August 2026','10 Aug 2026',8500,3],['Ali Raza','August 2026','10 Aug 2026',9000,4]].map((x:any)=><tr key={x[0]}><td className="px-5 py-4 font-bold">{x[0]}<div className="text-xs text-slate-400 font-normal">HA-2400{x[4]}</div></td><td className="px-5 text-slate-500">{x[1]}</td><td className="px-5 text-slate-500">{x[2]}</td><td className="px-5 font-bold">{money(x[3])}</td><td className="px-5">{paid.includes(x[4])?<Badge color="green">Paid</Badge>:<Badge color={x[4]===2?'amber':'rose'}>{x[4]===2?'Partial':'Unpaid'}</Badge>}</td><td className="px-5"><button onClick={()=>setPaid(p=>p.includes(x[4])?p.filter(i=>i!==x[4]):[...p,x[4]])} className="btn-small">{paid.includes(x[4])?<Printer size={14}/>:<Check size={14}/>} {paid.includes(x[4])?'Receipt':'Mark paid'}</button></td></tr>)}</Table></>}
function Attendance(){const [states,setStates]=useState<Record<number,string>>({1:'Present',2:'Present',3:'Present',4:'Absent',5:'Late'});return <><PageHead eyebrow="Daily register" title="Attendance" desc="Mark student attendance for Thursday, 20 August 2026." action={<button className="btn-secondary" onClick={()=>window.print()}><Printer size={16}/> Print register</button>}/><div className="card p-5 mb-5 flex flex-wrap items-center gap-4"><label className="label !mt-0">Class / section<select className="input mt-2 w-44"><option>Grade 8 · A</option><option>Grade 7 · B</option></select></label><div className="h-10 w-px bg-slate-200 hidden sm:block"/><div><div className="text-xs text-slate-400">Today’s summary</div><div className="font-bold mt-1"><span className="text-emerald-600">3 present</span> · <span className="text-rose-600">1 absent</span> · <span className="text-amber-600">1 late</span></div></div><button className="btn-primary ml-auto"><Check size={16}/> Save attendance</button></div><Table headers={['Student','Class','Present','Absent','Leave','Late']}>{studentsSeed.map(s=><tr key={s.id}><td className="px-5 py-4 font-bold">{s.name}<div className="font-normal text-xs text-slate-400">{s.admissionNo}</div></td><td className="px-5 text-slate-500">{s.className} · {s.section}</td>{['Present','Absent','Leave','Late'].map(v=><td className="px-5" key={v}><button onClick={()=>setStates({...states,[s.id]:v})} className={`size-7 rounded-full border grid place-items-center ${states[s.id]===v?(v==='Present'?'bg-emerald-500 border-emerald-500':v==='Absent'?'bg-rose-500 border-rose-500':v==='Late'?'bg-amber-400 border-amber-400':'bg-blue-400 border-blue-400'):'border-slate-200'}`}>{states[s.id]===v&&<Check size={14} className="text-white"/>}</button></td>)}</tr>)}</Table></>}
function Exams(){return <><PageHead eyebrow="Academics" title="Examinations & results" desc="Create exams, enter marks and generate report cards." action={<button className="btn-primary"><Plus size={17}/> Create examination</button>}/><div className="grid lg:grid-cols-[.8fr_1.2fr] gap-5"><div className="card p-5"><h3>Examinations</h3>{[['Mid-Term Examination','26 Aug 2026','Grade 8, 9','Upcoming'],['Monthly Assessment','02 Sep 2026','Grade 5, 6','Upcoming'],['First Term Examination','15 Jul 2026','All classes','Completed']].map(x=><div className="border-b last:border-0 border-slate-100 py-4" key={x[0]}><div className="flex justify-between"><b className="text-sm">{x[0]}</b><Badge color={x[3]==='Completed'?'green':'blue'}>{x[3]}</Badge></div><div className="text-xs text-slate-500 mt-2">{x[1]} · {x[2]}</div></div>)}</div><div className="card p-5"><div className="flex justify-between"><div><h3>Recent results</h3><p className="text-xs text-slate-400 mt-1">First Term Examination · Grade 8</p></div><button className="btn-small"><Printer size={14}/> Report cards</button></div><Table headers={['Rank','Student','Total marks','Percentage','Grade']} >{[['01','Ayesha Khan','472 / 500','94.4%','A+'],['02','Fatima Noor','451 / 500','90.2%','A+'],['03','Muhammad Hamza','428 / 500','85.6%','A']].map(x=><tr key={x[0]}><td className="px-3 py-3 font-bold text-[#263d83]">{x[0]}</td><td className="px-3 py-3 font-bold">{x[1]}</td><td className="px-3 py-3">{x[2]}</td><td className="px-3 py-3">{x[3]}</td><td className="px-3 py-3"><Badge color="green">{x[4]}</Badge></td></tr>)}</Table></div></div></>}
function Staff({role}:{role:Role}){return <><PageHead eyebrow="People" title="Staff & HR" desc={role==='owner'?'Manage staff profiles, attendance, payroll and leave.':'View staff directory and mark staff attendance.'} action={<button className="btn-primary"><Plus size={17}/> Add staff member</button>}/><div className="grid sm:grid-cols-3 gap-4 mb-5"><Stat label="Teaching staff" value="42" note="Across 12 classes" icon={Users}/><Stat label="Present today" value="39 / 42" note="3 on leave" icon={ClipboardCheck} tone="green"/>{role==='owner'&&<Stat label="Payroll this month" value="Rs. 1.86m" note="Due on 31 August" icon={WalletCards} tone="gold"/>}</div><Table headers={['Staff member','Designation','Assigned class','Contact','Status',...(role==='owner'?['Salary']:[])]}>{[['Sara Ali','Senior Teacher','Grade 5 · A','0300 1112233'],['Omar Farooq','Subject Teacher','Grade 7 · B','0312 2223344'],['Hina Malik','Class Teacher','Nursery · A','0333 5556677']].map(x=><tr key={x[0]}><td className="px-5 py-4 font-bold">{x[0]}</td><td className="px-5 text-slate-500">{x[1]}</td><td className="px-5">{x[2]}</td><td className="px-5 text-slate-500">{x[3]}</td><td className="px-5"><Badge color="green">Present</Badge></td>{role==='owner'&&<td className="px-5 font-bold">{money(58000)}</td>}</tr>)}</Table></>}
function Timetable(){const days=['Monday','Tuesday','Wednesday','Thursday','Friday'];const rows=['08:00 – 08:40','08:40 – 09:20','09:40 – 10:20','10:20 – 11:00','11:20 – 12:00'];const subs=['Mathematics','English','Physics','Urdu','Computer'];return <><PageHead eyebrow="Scheduling" title="Timetable" desc="Weekly class schedule for Grade 8 · Section A." action={<button className="btn-secondary" onClick={()=>window.print()}><Printer size={16}/> Print timetable</button>}/><div className="card overflow-auto print-card"><table className="w-full min-w-[760px] text-sm"><thead><tr><th className="p-4 text-left bg-slate-50 text-xs text-slate-400">TIME</th>{days.map(d=><th className="p-4 text-left bg-slate-50 text-xs text-slate-400" key={d}>{d}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr className="border-t border-slate-100" key={r}><td className="p-4 text-xs text-slate-400 whitespace-nowrap">{r}</td>{days.map((_,j)=><td className="p-2" key={j}><div className={`rounded-lg p-3 ${j===2&&i===2?'bg-amber-50':'bg-indigo-50/70'}`}><b className="text-xs text-[#263d83]">{subs[(i+j)%subs.length]}</b><div className="text-[10px] text-slate-500 mt-1">Mr. {['Khan','Ali','Raza'][j%3]}</div></div></td>)}</tr>)}</tbody></table></div></>}
function Reports({role}:{role:Role}){return <><PageHead eyebrow="Insights" title="Reports & analytics" desc="Print-ready summaries for school operations." action={<button className="btn-secondary" onClick={()=>window.print()}><Printer size={16}/> Print report</button>}/><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{[['Fee collection report','Daily, monthly and yearly collections by class','Rs. 1.84m'],['Defaulter report','Unpaid fees by month and class','142 students'],['Attendance summary','Class-wise attendance and eligibility','94.2% average'],['Exam result summary','Grades, positions and toppers','86% pass rate'],...(role==='owner'?[['Income vs expense','Fees in against salaries and expenses','Rs. 1.2m net'],['Student strength','Enrollment growth by class','1,248 enrolled']]:[])].map((x:any)=><div className="card p-5 hover:border-[#bdc8f2] transition" key={x[0]}><div className="size-10 bg-indigo-50 text-[#263d83] rounded-xl grid place-items-center"><FileBarChart size={19}/></div><h3 className="mt-5 text-base">{x[0]}</h3><p className="text-xs text-slate-500 mt-2">{x[1]}</p><div className="flex justify-between items-center mt-6 pt-4 border-t border-slate-100"><b className="text-sm">{x[2]}</b><button className="text-xs text-[#263d83] font-bold">Open report <ArrowUpRight size={14} className="inline"/></button></div></div>)}</div></>}
function Expenses(){return <><PageHead eyebrow="Finance · Owner only" title="Expense management" desc="Track school operating costs against collected fees." action={<button className="btn-primary"><Plus size={17}/> Log expense</button>}/><div className="grid sm:grid-cols-3 gap-4 mb-5"><Stat label="Expenses this month" value="Rs. 438,200" note="12 transactions" icon={CircleDollarSign} tone="gold"/><Stat label="Largest category" value="Salaries" note="Rs. 310,000 · 71%" icon={BarChart3}/><Stat label="Net operating income" value="Rs. 1.2m" note="This academic month" icon={Activity} tone="green"/></div><Table headers={['Date','Category','Description','Amount','Recorded by']} >{[['18 Aug 2026','Utilities','Electricity bill · August',42000,'Muhammad Ali'],['15 Aug 2026','Supplies','Classroom stationery',18600,'Muhammad Ali'],['01 Aug 2026','Salaries','Monthly payroll',310000,'Muhammad Ali']].map(x=><tr key={x[2]}>{x.map((v,i)=><td className={`px-5 py-4 ${i===2?'font-bold':''}`} key={String(v)}>{i===3?money(v as number):v}</td>)}</tr>)}</Table></>}
function SettingsPage(){return <><PageHead eyebrow="Administration · Owner only" title="Settings & backup" desc="School profile, academic year, users and local data safety."/><div className="grid lg:grid-cols-2 gap-5"><div className="card p-6"><h3>School profile</h3><div className="grid gap-4 mt-5"><label className="label">School name<input className="input mt-2" defaultValue="Horizon Academy"/></label><label className="label">Address<input className="input mt-2" defaultValue="21 Education Avenue, Lahore"/></label><label className="label">Contact number<input className="input mt-2" defaultValue="+92 42 1234567"/></label><button className="btn-primary w-fit">Save changes</button></div></div><div className="card p-6"><h3>Backup & restore</h3><p className="text-sm text-slate-500 mt-2">Keep a copy of your local school data on a USB drive.</p><div className="rounded-xl bg-amber-50 text-amber-800 p-4 mt-5 text-sm"><b>Backup reminder</b><p className="mt-1 text-xs">Last backup was 4 days ago. We recommend backing up weekly.</p></div><div className="flex gap-3 mt-5"><button className="btn-primary"><Archive size={16}/> Backup now</button><button className="btn-secondary">Restore backup</button></div><div className="border-t mt-6 pt-5 text-xs text-slate-400">App version 1.0.0 · Local storage · Academic year 2024–25</div></div></div></>}
function Cards(){return <><PageHead eyebrow="Documents" title="ID cards & certificates" desc="Generate print-ready school documents with your school profile." action={<button className="btn-primary"><Printer size={16}/> Print selected</button>}/><div className="grid md:grid-cols-3 gap-5">{[['Student ID card','Photo, class, admission number'],['Character certificate','Formal character certificate template'],['Bonafide certificate','Proof of enrollment document'],['Leaving certificate','Student leaving / transfer certificate']].map((x,i)=><div className="card p-5" key={x[0]}><div className={`h-32 rounded-xl ${i===0?'bg-[#172a62]':'bg-slate-100'} p-4 ${i===0?'text-white':''}`}><div className="flex justify-between"><GraduationCap size={21}/><span className="text-[9px] tracking-widest uppercase opacity-60">Horizon</span></div><div className="mt-12 text-xs font-bold">{i===0?'AYESHA KHAN':'CERTIFICATE PREVIEW'}</div></div><h3 className="text-base mt-5">{x[0]}</h3><p className="text-xs text-slate-500 mt-1">{x[1]}</p><button className="btn-small mt-5 w-full justify-center"><Printer size={14}/> Open template</button></div>)}</div></>}

export default App